version: '3'
services:
  mongo:
    image: 'mongo:4.4.14'
    restart: 'always'
    ports:
      - '27017:27018'
    networks:
      - beckn_net
    logging:
      driver: none
  ampq:
    image: 'rabbitmq:3.11.0'
    restart: 'always'
    ports:
      - '5672:5672'
    networks:
      - beckn_net
    logging:
      driver: none
  redis:
    image: 'redis:7.0.0'
    restart: 'always'
    expose:
      - '6379'
    networks:
      - beckn_net
    logging:
      driver: none
  protocol-server:
    build: './'
    image: elevate/protocol-server:1.0
    volumes:
      - ./:/var/
    ports:
      - '5000:5000'
    command: ['nodemon', 'src/app.ts']
    depends_on:
      - mongo
    networks:
      - beckn_net
networks:
  beckn_net:
    external: false
volumes:
  mongo-data:
